name: Build nbfc

on:
  push:
  pull_request:

jobs:
  build_job:
    name: build nbfc for releasing
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: mono:latest
            options: -v ${{ github.workspace }}:/nbfc
            run: |
                cd /nbfc
                chmod +x build.sh
                ./build.sh
